### ISSUE TITLE
isuue with grid and alligning bars on UI

### ISSUE THREAD

**Issue by Drukhi** [blooblahguy/bdCore#11]
to describe it two simple screenshots:
![wowscrnshot_072418_145123](https://user-images.githubusercontent.com/41521167/43139084-23ee7062-8f51-11e8-98bc-856b7bde5ad3.jpg)
![wowscrnshot_072418_145141](https://user-images.githubusercontent.com/41521167/43139085-24086a08-8f51-11e8-9676-81457e2edf1c.jpg)

**Comment by blooblahguy** [comment]
This issue should be resolved with the latest update. I was not able to replicate on my end but I believe I know the source of the issue. Let me know if that resolves it for you.

**Comment by Drukhi** [comment]
This is solved now. Great work!
