### ISSUE TITLE
LUA Error 

### ISSUE THREAD

**Issue by zeddicius** [blooblahguy/bdCore#4]
Message: Interface\AddOns\bdNameplates\core.lua:717: Usage: UnitName("unit")
Time: 12/08/17 16:30:19
Count: 1
Stack: Interface\AddOns\bdNameplates\core.lua:717: Usage: UnitName("unit")
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
[C]: in function `UnitName'
Interface\AddOns\bdNameplates\core.lua:717: in function <Interface\AddOns\bdNameplates\core.lua:680>
Interface\AddOns\bdNameplates\core.lua:1031: in function <Interface\AddOns\bdNameplates\core.lua:1030>
(tail call): ?
(tail call): ?
Interface\AddOns\bdCore\lib\oUF\ouf.lua:200: in function `UpdateAllElements'
Interface\AddOns\bdCore\lib\oUF\ouf.lua:756: in function <Interface\AddOns\bdCore\lib\oUF\ouf.lua:711>

Locals: errorMessage = "Interface\AddOns\bdNameplates\core.lua:717: Usage: UnitName("unit")"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0

Message: Interface\AddOns\bdNameplates\core.lua:717: Usage: UnitName("unit")
Time: 12/08/17 16:30:18
Count: 39
Stack: Interface\AddOns\bdNameplates\core.lua:717: Usage: UnitName("unit")
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
[C]: in function `UnitName'
Interface\AddOns\bdNameplates\core.lua:717: in function <Interface\AddOns\bdNameplates\core.lua:680>
Interface\AddOns\bdNameplates\core.lua:1031: in function <Interface\AddOns\bdNameplates\core.lua:1030>
(tail call): ?
(tail call): ?
(tail call): ?

Locals: errorMessage = "Interface\AddOns\bdNameplates\core.lua:717: Usage: UnitName("unit")"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0

Message: Interface\AddOns\bdNameplates\core.lua:717: Usage: UnitName("unit")
Time: 12/08/17 16:30:19
Count: 26
Stack: Interface\AddOns\bdNameplates\core.lua:717: Usage: UnitName("unit")
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
[C]: in function `UnitName'
Interface\AddOns\bdNameplates\core.lua:717: in function <Interface\AddOns\bdNameplates\core.lua:680>
Interface\AddOns\bdNameplates\core.lua:1028: in function <Interface\AddOns\bdNameplates\core.lua:1027>

Locals: errorMessage = "Interface\AddOns\bdNameplates\core.lua:717: Usage: UnitName("unit")"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0

**Comment by blooblahguy** [comment]
This was part of a temporary test that got through, removed/fixed
