### ISSUE TITLE
Broken Fancymenu

### ISSUE THREAD

**Issue by Kewlie** [blooblahguy/bdCore#5]
1x bdCore\scripts\fancymenu.lua:115: bad argument #1 to 'match' (string expected, got nil)
[C]: in function `match'
bdCore\scripts\fancymenu.lua:115: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "%d+x(%d+)"
(*temporary) = "string expected, got nil"

**Comment by blooblahguy** [comment]
Are you on a PC or Mac? What resolution are you playing the game on? This error is because GetScreenResolution is returning nil, will look into a workaround. Fancy Menu is currently disabled in build because of issues with SecuredFrames

**Comment by Kewlie** [comment]
laptop and pc running windows 10 home both on 1920x1080 resolution
laptop has nvidia GeForce 1050 gtx, although the intel chipset is the one that sets resolution ill set it to maintain aspect ratio and see what happens
pc has GeForce 1060 gt

**Comment by xtda** [comment]
Are you playing in windowed mode by any chance? 
If a game is started in windowed mode GetCurrentResolution will return nil instead of the index so [this will fail](https://github.com/blooblahguy/bdCore/blob/master/config/config.lua#L148) because its trying to get GetScreenResolutions()[0]

**Comment by blooblahguy** [comment]
I've updated a lot of the code surrounding window scale and this should all be fixed. Though fancy menu itself is still disabled while I continue developing it
