### ISSUE TITLE
GMOTD script

### ISSUE THREAD

**Issue by Kewlie** [blooblahguy/bdCore#6]
5x bdCore\scripts\gmotd.lua:46: attempt to index field 'persistent' (a nil value)
bdCore\scripts\gmotd.lua:46: in function <bdCore\scripts\gmotd.lua:34>

Locals:
self = <unnamed> {
 0 = <userdata>
 header = <unnamed> {
 }
 button = <unnamed> {
 }
 background = <unnamed> {
 }
 border = <unnamed> {
 }
 text = <unnamed> {
 }
}
event = "GUILD_ROSTER_UPDATE"
message = nil
guild = "The Fallen"
msg = "Antorus 8:30pm every Wednesdsay and Sunday. Be there!"
(*temporary) = nil
(*temporary) = "Antorus 8:30pm every Wednesdsay and Sunday. Be there!"
(*temporary) = 53
(*temporary) = "Officer Alt"
(*temporary) = "attempt to index field 'persistent' (a nil value)"
c = <table> {
}
gmotd = <unnamed> {
 0 = <userdata>
 header = <unnamed> {
 }
 button = <unnamed> {
 }
 background = <unnamed> {
 }
 border = <unnamed> {
 }
 text = <unnamed> {
 }
}

**Comment by blooblahguy** [comment]
Looks like sometimes GUILD_ROSTER_UPDATE can fire before ADDON_LOADED and the variables weren't loaded yet. Wrapped this script in a "loaded_bdcore" trigger.
