### ISSUE TITLE
Problem with block (UiErrorsFrame and BdCore Alt Power)

### ISSUE THREAD

**Issue by Stigmat92** [blooblahguy/bdCore#7]
You can not click to target in the block area
yellow circle is my cursor

Sorry , dont speak english :(

![wowscrnshot_012318_112422](https://user-images.githubusercontent.com/27617367/35271100-520d1476-0031-11e8-8018-b24a950d2f3f.jpg)
![screenshot_1](https://user-images.githubusercontent.com/27617367/35271097-51a55980-0031-11e8-81d8-d45d1d010b3a.png)
![screenshot_2](https://user-images.githubusercontent.com/27617367/35271098-51cc2c04-0031-11e8-82b2-992357b92657.png)
![screenshot_3](https://user-images.githubusercontent.com/27617367/35271099-51eba0b6-0031-11e8-88bd-e865cce6c880.png)

**Comment by VincentDawn** [comment]
Also having this issue. Moving the bar resulted in a LUA error and I was then able to click through it fine. The issue returns after a UI reload.

**Comment by SirNorek** [comment]
Temporary solution, unlocking and relocking the BDCore instantly makes the frames click through properly. Unfortunately you have to do this every time you login or reloadUI.

**Comment by SirNorek** [comment]
This now seems to be solved in the current version 👍

**Comment by Stigmat92** [comment]
Merci !
